name: Tranzit (Android .apk and .aab build)
on:
  workflow_dispatch:  # manual trigger only

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk-version: 25.2.9519653

      - name: Setup Java (required for Gradle)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install frontend dependencies
        run: npm install

      - name: Create .env file
        run: cp sample.env .env

      - name: Add Rust Android targets (ARM64 + x86_64)
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Build universal APK (ARM64 and x86_64)
        run: npm run tauri android build -- --target aarch64 x86_64

      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: tranzit-android-apk-arm64
          path: src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk

      - name: Build AAB (includes all architectures)
        run: npm run tauri android build -- --aab --target aarch64 x86_64

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: tranzit-android-aab
          path: src-tauri/gen/android/app/build/outputs/bundle/universalRelease/*.aab
