name: Tranzit (macOS Installer - Universal DMG)

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add macOS targets
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install npm dependencies
        run: npm install

      - name: Install Tauri CLI globally
        run: npm install --global @tauri-apps/cli

      - name: Create .env file
        run: cp sample.env .env

      - name: Build Tauri app (Universal macOS)
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: tauri-macos-universal-dmg
          path: /Users/runner/work/tranzit/tranzit/src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error
