name: Tranzit (AppImage Build)

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build-appimage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri AppImage
        run: |
          NO_STRIP=true npm run tauri build

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-ubuntu-20.04
          path: src-tauri/target/release/bundle/appimage/*.AppImage
